### ISSUE TITLE
Fails to build with newer ICU version (they enforce namespace)

### ISSUE THREAD

**Issue by stoecker** [giggls/mapnik-german-l10n#10]
For newer ICU version the define U_USING_ICU_NAMESPACE must be defined. One possible solution:

`diff -ur osml10n-20180913/icutranslit/Makefile osml10n-20180913_fix/icutranslit/Makefile
--- osml10n-20180913/icutranslit/Makefile       2018-08-19 13:12:56.000000000 +0200
+++ osml10n-20180913_fix/icutranslit/Makefile   2018-09-13 19:15:28.575183123 +0200
@@ -10,7 +10,7 @@
 OBJ = osml10n_translit.o
 
 %.o: %.cpp
-       $(CXX) $(CFLAGS) -c $<
+       $(CXX) $(CFLAGS) -c $< -DU_USING_ICU_NAMESPACE=1
 
 osml10n_translit.so: osml10n_translit.o
        $(CXX) -shared -o $@ $< $(LIBS)
`

**Comment by giggls** [comment]
Which Version did you try to build with?
Version 60.2 from Debian testing still seems to work just fine.

**Comment by stoecker** [comment]
> Which Version did you try to build with?

As you already found out: 62.1

Sorry for not telling. I never checked the number, as it worked before and the fail was for openSUSE Tumbleweed and thus a new ICU version must have been the reason :-)
