### ISSUE TITLE
missing osml10n_street_abbrev_* functions?

### ISSUE THREAD

**Issue by rrzefox** [giggls/mapnik-german-l10n#11]
First off: I'm not sure if this is really a bug or just a setup error - but you can probably spot this more quickly than I can.

On my tileserver, some tiles fail to rerender after an Update from Ubuntu 16.04 to 18.04 because they throw SQL errors like this:
```
Mapnik datasource exception: Postgis Plugin: ERROR:  column "osml10n_street_abbrev_ja" does not exist
#012LINE 1: select osml10n_street_abbrev_ja-Latn('Kōzai Minamimachi')
#012               ^
#012QUERY:  select osml10n_street_abbrev_ja-Latn('Kōzai Minamimachi')
#012CONTEXT:  PL/pgSQL function osml10n_street_abbrev(text,text) line 9 at EXECUTE
#012PL/pgSQL function osml10n_gen_combined_name(text,text,hstore,boolean,boolean,text,boolean,boolean,boolean) line 144 at assignment
#012PL/pgSQL function osml10n_get_name_from_tags(hstore,boolean,boolean,boolean,text,text,geometry) line 53 at RETURN
#012PL/pgSQL function osml10n_get_streetname_from_tags(hstore,boolean,boolean,text,text,geometry,text) line 7 at RETURN
#012in executeQuery Full sql was: 'SELECT ST_AsBinary("way") AS geom,"highway","junction","name","ref" FROM (SELECT
#012    way,
#012    highway,
#012    junction,
#012    ref,
#012    localized_streetname as name,
#012    NULL AS way_pixels
#012  FROM planet_osm_point_de
#012  WHERE highway = 'motorway_junction' OR highway = 'traffic_signals' OR junction = 'yes'
#012UNION ALL
#012  SELECT
#012    way,
#012    highway,
#012    junction,
#012    ref,
#012    name,
#012    way_area/NULLIF(38.2185::real*38.2185::real,0) AS way_pixels
#012  FROM planet_osm_polygon_de
#012  WHERE junction = 'yes'
#012  ORDER BY way_pixels DESC NULLS LAST
#012) AS junctions WHERE "way" && ST_SetSRID('BOX3D(14852020.34392288 3972279.485924038,14969427.61936892 4089686.761370071)'::box3d, 3857)'
```
(this is the metatile at x=3624 y=1624 z=12)
so it seems that somewhere in a deep callstack, localized_streetname _in very rare cases_ internally calls osml10n_street_abbrev_ja which does not exist?
This only ever happens with osml10n_street_abbrev_ko, _sr or _ja. I see that other functions like osml10n_street_abbrev_de or _fr or _ru do exist. So should _ko/_sr/_ja exist too? If not, why is it called?

**Comment by giggls** [comment]
Did you re-build osml10n for postgresql-10?
Can you reproduce the failure using render_single_tile.py?
I consider it unlikely to find the bug if you can not provide a failing SQL call :(

**Comment by giggls** [comment]
OK, I seem to have found a failing example:
SELECT localized_streetname FROM planet_osm_point WHERE osm_id=2329329815;

**Comment by giggls** [comment]
Looks like those name:XX-Latn tags will do more harm than good. Working on a fix.

**Comment by rrzefox** [comment]
Yes I did rebuild osml10n for postgresql-10. And the full SQL was quoted (after "Full sql was:" above), although of course your failing is example is much more helpful. After looking at `plpgsql/street_abbrv.sql`, I'd now guess that the catching of the undefined_function exception in osml10n_street_abbrev does not work with postgresql-10?

**Comment by rrzefox** [comment]
fix works, thanks a lot for the quick fix!
