### ISSUE TITLE
get_localized_name_from_tags.sql

### ISSUE THREAD

**Issue by amcu** [giggls/mapnik-german-l10n#13]
get_localized_name_from_tags.sql line 162
"regexp_match(" should be changes to "regexp_matches("
otherwise postgis Extension l10n thrown exceptions on certain queries

**Comment by amcu** [comment]
someone already was quicker a month ago with his pull request. issue is with postgresql 9.x and not anymore with pgsql10.
better would be a check for installed pg Version to generate correct working get_localized_name_from_tags.sql

**Comment by giggls** [comment]
A version check is not needed as regexp_matches seems to work in Postgresql 9.x and Postgresql 10.x.

I was waiting for a positive answer if the SQL query from my comment for pull request #12 works as expected in Postgresql 9.x as well before merging it.
