### ISSUE TITLE
Mention curl as a dependency

### ISSUE THREAD

**Issue by otbutz** [giggls/mapnik-german-l10n#17]
I installed the dependencies manually and missed `curl`: https://github.com/giggls/mapnik-german-l10n/blob/0060ef7af260648c124af96d361076a87e03ced3/gen_osml10n_extension.sh#L13

Therefor the script generated an empty `country_osm_grid.sql` and i wasn't able to install the extension.

I would suggest to
1. mention curl as a dependency
2. check the return code of the curl download in the script or at least check if gunzip returned with exit code 0

Edit: fixed URL

**Comment by giggls** [comment]
Looks like I replaces wget by curl at some stage.
