### ISSUE TITLE
Replace Thai transliteration library

### ISSUE THREAD

**Issue by stephankn** [giggls/mapnik-german-l10n#20]
Please switch the Thai transliteration library.

I checked this area:
https://www.openstreetmap.de/karte.html?zoom=16&lat=18.86776&lon=99.14068&layers=B000TF

For example this node:
https://www.openstreetmap.org/node/4542027125

with the Thai name:
ห้องสมุดประชาชน

is being rendered as
![image](https://user-images.githubusercontent.com/251140/65439945-49385f00-de28-11e9-8560-28fde87201f1.png)

"ongtmutpnatatn"

The python library here:
https://pypi.org/project/tltk/

gives the much better RTGS transliteration of
hongsamut prachachon

     out = tltk.nlp.th2roman(txt)

Probably even capitalize the initial characters.

**Comment by giggls** [comment]
Have a look at https://github.com/giggls/mapnik-german-l10n/blob/master/thaitranscript/thai_transcript.sql do you think that split_by_alphabet is still needed?

**Comment by giggls** [comment]
Do you understand what `<s/>` is for?

```python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tltk
>>> tltk.nlp.th2roman('ห้องสมุดประชาชน')
'hongsamut prachachon <s/>'
>>> 
```

**Comment by giggls** [comment]
I will just discard this stuff then, right?

**Comment by stephankn** [comment]
Discarding sounds right.
