### ISSUE TITLE
Abkürzungen für Strassen / Orte in Französisch

### ISSUE THREAD

**Issue by chatelao** [giggls/mapnik-german-l10n#22]
Guten Tag, es gibt auch im Französischen jede Menge an Abkürzungen für Orte / Strassen Prefixes:

- https://www.canadapost.ca/tools/pg/manual/PGaddress-f.asp#1460716

Häufig gebraucht:
- Chemin: Ch
- Route: Rte

**Comment by giggls** [comment]
Ja klar, die gibt es noch in vielen weiteren Sprachen, siehe auch meine talks.

Mein französisch ist aber ganz sicher nicht gut genug das selbst zu implementieren. Schau in [street_abbrv.sql](https://github.com/giggls/mapnik-german-l10n/blob/master/plpgsql/street_abbrv.sql) ich freue mich über pull-requests!

Einfach osml10n_street_abbrev_fr äquivalent zum Beispiel zu osml10n_street_abbrev_en erzeugen. Ich prüfe den fertigen Code dann gerne auf korrektes Funktionieren.

Mit sind Muttersprachler (native speakers) an dieser Stelle wichtig, denn es geht auch darum dass solche Abkürzungen überrhaupt gebräuchlich sind und das kann ich nun schon gar nicht abschätzen.

**Comment by chatelao** [comment]
Mein Vater ist frz. Muttersprache. Ich schaue mir die gängigen und sinnvoll
möglichen Abkürzungen mit ihm an.

Sven Geggus <notifications@github.com> schrieb am Mo., 14. Okt. 2019, 17:04:

**Comment by chatelao** [comment]
Erste Fragestellung @giggls 

Wie ist mit Begriffen umzugehen, die es Englisch als auch Französisch identisch gibt, die aber anders abgekürzt werden:

Bsp.: https://www.openstreetmap.de/karte.html?zoom=18&lat=46.80203&lon=7.1506&layers=B000TT

1. Boulevard: "Blvd." (Englisch), eigentlich "Boul"
1. Avenue: "Ave." (Englisch), eigentlich "Av"

Gibt es eine Liste mit den dominanten Sprachen am Ort der Übersetzung, die verwendet werden könnte?
- Die Reihenfolge in ```osml10n_street_abbrev_all``` müsste in Abhängigkeit der ortsgängigen Sprachen ausgeführt werden. Keine Ahnung ob das so möglich ist?

**Comment by giggls** [comment]
Der Code weiß nicht in welcher Sprache der lokale Name geschrieben ist. Woher auch?

Straßen sind nur ganz selten mehrsprachig getaggt. Zeige mir ein Real-World Beispiel wo der gegenwärtig verwendete Code schief geht. Es gibt eine harte Reihenfolge der Priorität lateinischer Sprachen, die genommen werden, wenn die Zielsprache nicht zur Verfügung steht:
latin_langs text[] := '{"en","fr","es","pt","de"}';

**Comment by chatelao** [comment]
Tönt unter den gegebenen Umständen vernünftig.

Schief geht er hier in Fribourg (Im Üchtland):
- https://c.tile.openstreetmap.de/18/136279/92414.png (Bloulevard als Blvd. statt Boul./Bd)
- https://c.tile.openstreetmap.de/18/136280/92412.png (Avenue als Ave. statt Av.)

**Comment by giggls** [comment]
Da kann man sich vielleicht eine Eigenschaft des französischen zu Nutze machen, dass es dort meist heißt: "Avenue de la ..." während es im englischen "... Avenue" ist.
Also "Avenue " abkürzen als "Av. ", " Avenue" abkürzen als " Ave."

Nicht vergessen, dass die ganze Sache hier sowieso keine 100% Lösung ist. In den meisten Fällen ist die lokalisierte Version besser aber ganz sicher nicht in allen.

**Comment by chatelao** [comment]
Die Prä-/Postfix Unterscheidung ist eine gute Idee. Ich schaue mir das mal an.

**Comment by dieterdreist** [comment]
Am Do., 17. Okt. 2019 um 09:57 Uhr schrieb Sven Geggus <
notifications@github.com>:

> Da kann man sich vielleicht eine Eigenschaft des französischen zu Nutze
> machen, dass es dort meist heißt: "Avenue de la ..." während es im
> englischen "... Avenue" ist.
> Also "Avenue " abkürzen als "Av. ", " Avenue" abkürzen als " Ave."
>
> Nicht vergessen, dass die ganze Sache hier sowieso keine 100% Lösung ist.
> In den meisten Fällen ist die lokalisierte Version besser aber ganz sicher
> nicht in allen.
>
>

die Präpositionen sind im Französischen dort, wo es um Orte geht, also
Avenue d'Italie, oder Avenue de Choisy, oder Avenue d'Ivry, während bei
Personen, und das sind ebenfalls sehr viele, keine Präpositionen
dazukommen: Avenue Paul Vaillant-Couturier oder Avenue Marx Dormoy oder
Avenue Victor Hugo,

**Comment by dieterdreist** [comment]
Am Do., 17. Okt. 2019 um 10:17 Uhr schrieb Martin Koppenhoefer <
dieterdreist@gmail.com>:

>
>
> Am Do., 17. Okt. 2019 um 09:57 Uhr schrieb Sven Geggus <
> notifications@github.com>:
>
>> Da kann man sich vielleicht eine Eigenschaft des französischen zu Nutze
>> machen, dass es dort meist heißt: "Avenue de la ..." während es im
>> englischen "... Avenue" ist.
>> Also "Avenue " abkürzen als "Av. ", " Avenue" abkürzen als " Ave."
>>
>> Nicht vergessen, dass die ganze Sache hier sowieso keine 100% Lösung ist.
>> In den meisten Fällen ist die lokalisierte Version besser aber ganz sicher
>> nicht in allen.
>>
>>
>
> die Präpositionen sind im Französischen dort, wo es um Orte geht, also
> Avenue d'Italie, oder Avenue de Choisy, oder Avenue d'Ivry, während bei
> Personen, und das sind ebenfalls sehr viele, keine Präpositionen
> dazukommen: Avenue Paul Vaillant-Couturier oder Avenue Marx Dormoy oder
> Avenue Victor Hugo,
>


als kleine Ergänzung: im Französischen steht Avenue oder Boulevard oder Rue
etc. immer vorn (wie auch im Italienischen und evtl. in allen romanischen
Sprachen), während es im Englischen hinten steht: Paris Avenue, oder 5th
Avenue, etc.

**Comment by giggls** [comment]
Eben und genau das kann man sich zu Nutze machen um in einem Fall Av. im anderen Fall Ave. abzukürzen. BTW, wenn wir schon dabei sind, du könntest italienische Abkürzungen beitragen. In Südtirol gibt es vermutlich sogar Städte wo das sinnvoll ist, weil deutsch und italienisch gerendert wird.

Als Vorlage kann generell auch das hier dienen:
https://github.com/mapbox/geocoder-abbreviations/tree/master/tokens

@chatelao: Ergänze bitte auch tests für solche Straßennamen.

**Comment by dieterdreist** [comment]
Am Do., 17. Okt. 2019 um 10:41 Uhr schrieb Sven Geggus <
notifications@github.com>:

> Eben und genau das kann man sich zu Nutze machen um in einem Fall Av. im
> anderen Fall Ave. abzukürzen. BTW, wenn wir schon dabei sind, du könntest
> italienische Abkürzungen beitragen. In Südtirol gibt es vermutlich sogar
> Städte wo das sinnvoll ist, weil deutsch und italienisch gerendert wird.
>


das habe ich (nicht alleine) bereits hier getan:
https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#Italiano_-_Italian

Frage: kürzt Ihr auch Vornamen ab? Das ist im italienischen ein großes
Thema, weil sehr viele Straßen nach Personen benannt sind, diese immer mit
Vor- und Nachnamen heißen, aber im Sprachgebrauch und ggf. auch auf Karten
sofern der Platz es erfordert, werden nur Straßenart und Nachname
verwendet. Bis auf Ausnahmen, wo eine unbedeutendere Persönlichkeit mit
demselben Nachnamen von einer bekannten Person unterschieden werden muss.
Z.B. Via Garibaldi (der Einiger Italiens) und Via Rosa Raimondi Garibaldi
(eine Frau mit demselben Nachnamen).
Nominatim war dem bisher leider nicht sehr aufgeschlossen gegenüber (der
Rat war, erstmal mit alt_name oder short_name das händisch zu machen, oder
die Personen mit wikidata zu vertaggen), ist aber auch Thema in anderen
Ländern, AFAIR Spanien.

Was man auch z.B. oft weglassen kann im italienischen sind Präpositionen:
anstatt "Via del Monte di Minchia" "Via Monte di Minchia".

**Comment by giggls** [comment]
Ich orientiere mich im allgemeinen daran wie das auf Straßenschildern und oder auf gedruckten Karten gemacht wird. Wenn Du in den Code schaust kannst du sehen, dass wir im deutschen Titel wie Doktor oder Professor abkürzen. Mal schaun, vielleicht baue ich am WE mal die Tabelle aus dem Wiki zumindest für einige weiterre Sprachen in das Script ein.

**Comment by chatelao** [comment]
Ihr seid lustig, die Tabelle.sieht doch sehr ähnlich jener, die ich aus der kanadischen Postempfehlung entworfen habe:

- https://github.com/chatelao/mapnik-german-l10n/blob/abbrv-fr/docs/canadian_post_abbreviations.md

Das kommt gut.

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Oct 2019, at 11:42, Sven Geggus <notifications@github.com> wrote:
> 
> Ich orientiere mich im allgemeinen daran wie das auf Straßenschildern und oder auf gedruckten Karten gemacht wird.


auf Schildern werden die Vornamen oft weggelassen, offiziell sind sie praktisch immer Namensbestandteil.

**Comment by giggls** [comment]
Sehe ich nicht wie man das automatisiert machen könnte. Gegen eine Liste wegzulassender Vornamen abgleichen? Echt?

**Comment by dieterdreist** [comment]
Am Do., 17. Okt. 2019 um 17:43 Uhr schrieb Sven Geggus <
notifications@github.com>:

> Sehe ich nicht wie man das automatisiert machen könnte. Gegen eine Liste
> wegzulassender Vornamen abgleichen? Echt?
>
>

Lonvias Vorschlag für Nominatim war, einen wikidata link für die Herkunft /
den Bezug des Straßennamens zu setzen, so dass man aus Wikidata sehen kann,
was Vorname und was Nachname ist (sofern das dort eingetragen ist). (Rein
hypothetisch, das ist nichts, was derzeit programmiert wird soweit ich
vermute).

**Comment by dieterdreist** [comment]
Alternativ könnte man eine Liste wenigstens der häufigsten Personen
pflegen, und wie man sie abkürzen kann. Es gibt (mind., aber sehen wirs mal
so für diesen Kontext) 2 Arten von Personen nach denen Straßen benannt
werden: Lokalhelden und allgemein bekannte (national oder international,
z.B. John Fitzgerald Kennedy). Die Lokalhelden werden wohl nur wenige Male
vorkommen (in ihrer Gegend), während die anderen immer und immer wieder
auftauchen. Für diese zweiten, allgemeinen Personen, wäre eine eigene Liste
vermutlich schaffbar und auch sinnvoller. Für die anderen könnte man es
über wikidata machen (was aber auch auf das cachen der Resultate und damit
auf eine eigene Liste hinausläuft, nur dass sie automatisch erstellt wäre).

Typischer Fall ist "Via Cavour", der mit vollem Namen "Camillo Paolo
Filippo Giulio Benso, conte di Cavour, di Cellarengo e di Isolabella"
heißt, oder auch "kurz" "Camillo Benso di Cavour" oder "Camillo Benso conte
di Cavour".  Oder halt einfach "Cavour".

**Comment by dieterdreist** [comment]
Am Do., 17. Okt. 2019 um 17:59 Uhr schrieb Martin Koppenhoefer <
dieterdreist@gmail.com>:

> Typischer Fall ist "Via Cavour", der mit vollem Namen "Camillo Paolo
> Filippo Giulio Benso, conte di Cavour, di Cellarengo e di Isolabella"
> heißt, oder auch "kurz" "Camillo Benso di Cavour" oder "Camillo Benso conte
> di Cavour".  Oder halt einfach "Cavour".
>
>


Hier ist sein Wikidata item: https://www.wikidata.org/wiki/Q166092
Wie man sieht ist es ggf. noch komplizierter, der Herr wäre mit einer Liste
von uns einfacher zu handeln, weil "Benso" ist der Nachname, "Cavour"
eigentlich nur eine Abkürzung seines Titels (bzw. Namensbestandteils, je
nachdem wie man es sieht) "Graf von Cavour", aber das ist der Name unter
dem er am bekanntesten ist.

**Comment by dieterdreist** [comment]
von Cavour finde ich über 1000 über Taginfo:
https://taginfo.openstreetmap.org/search?q=name%3Dvia+camillo+benso+

**Comment by chatelao** [comment]
Meine Lieben, aktuell kommt mindestens die "en/fr" Unterscheidung ein wenig voran:

- Erstes Wort, FR: abbrev=regexp_replace(abbrev,'^Avenue\M','Av.');
- Alle anderen EN: abbrev=regexp_replace(abbrev,'(?!^)Avenue\M','Ave.');

Any feedback welcome

**Comment by giggls** [comment]
Das sieht gut aus:

```SQL
sven=> select regexp_replace('Avenue de la gare','^Avenue\M','Av.');
 regexp_replace 
----------------
 Av. de la gare
(1 Zeile)

sven=> select regexp_replace('5th Avenue','(?!^)Avenue\M','Ave.');
 regexp_replace 
----------------
 5th Ave.
(1 Zeile)
```

Wobei ich mich frage ob man das `de la`  eigentlich ebenfalls abgekürzt wird.

@dieterdreist: Das mit den Vornamen ist mir zu kompliziert. Einen pull request würde ich trotzdem nehmen :)

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Oct 2019, at 18:52, Sven Geggus <notifications@github.com> wrote:
> 
> @dieterdreist: Das mit den Vornamen ist mir zu kompliziert. Einen pull request würde ich trotzdem nehmen :)
> 


nimmst du die short_name-Werte fall vorhanden in den tags wenn der name nicht passt?

**Comment by giggls** [comment]
Nein, kein Short name. Es geht hier primär um Lokalisierung, das scheint mir irgendwie gerade in Vergessenheit zu geraten.

Mir wäre außerdem nicht bekannt wie und ob man in Mapnik den zu rendernden String je nach Länge des Objekts unterschiedlich wählen kann.

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Oct 2019, at 22:25, Sven Geggus <notifications@github.com> wrote:
> 
> Mir wäre außerdem nicht bekannt wie und ob man in Mapnik den zu rendernden String je nach Länge des Objekts unterschiedlich wählen kann.


über placements 

https://github.com/mapnik/mapnik/wiki/TextSymbolizer

bin mir nicht sicher ob das bei Straßen funktionieren würde, aber bei Plätzen, Brücken und anderen Punkten geht es AFAIK damit.

**Comment by giggls** [comment]
Die Frage wäre ja wie ich ins SQL einen Kennwert für die gewünschte Länge des name Strings rein kriege. Momentan kürzt der Code einfach immer stur doof ab, auch wenn es aufgrund der Länge des Straßenobjektes nicht notwendig wäre.

**Comment by giggls** [comment]
Wenn das bei Straßen ohnehin keine Option ist, dann sollten wir diese Diskussion hiermit beenden, 
denn `osml10n_get_streetname_from_tags` wird derzeit ausschließlich für linienförmige Objekte verwendet. Wenn nicht, dann ist das ein Fehler im Kartenstil.

**Comment by giggls** [comment]
Hm, keine Regel ohne Außnahme!

Quebec Kanada:
1ere Avenue
2e Avenue

Ob man den Regulären Ausdruck so umbiegen kann, dass er das französisch abkürzt?

**Comment by chatelao** [comment]
Ich schaue mir das kurz an und schreibe den Patch.

Das Schwesterprojekt macht schon Fortschritte, aber ist noch nicht spruchreif: https://github.com/chatelao/osm-abbrev, insb.: https://github.com/chatelao/osm-abbrev/tree/master/src

**Comment by giggls** [comment]
Das hier scheint zu tun, kann man aber bestimmt noch schöner machen:

```diff
diff --git a/debian/control b/debian/control
index a1d1476..eeeb6b0 100644
--- a/debian/control
+++ b/debian/control
@@ -10,6 +10,9 @@ Standards-Version: 3.9.2
 
 Package: postgresql-11-osml10n
 Architecture: any
+# "postgis" is used as some kind of meta package here, because it
+# contains all dependencies for whatever version of PostGIS is available
+# on the Debian or Ubuntu intallation this code is going to get built
 Depends: ${shlibs:Depends}, ${misc:Depends}, postgresql-11, icu-devtools
 Recommends: postgresql-plpython3-11, python3-matplotlib, python3-pip, postgis
 Description: l10n package for generation of OSM based maps from PostGIS
diff --git a/plpgsql/street_abbrv.sql b/plpgsql/street_abbrv.sql
index 22c8c14..078f5ce 100644
--- a/plpgsql/street_abbrv.sql
+++ b/plpgsql/street_abbrv.sql
@@ -50,9 +50,10 @@ CREATE or REPLACE FUNCTION osml10n_street_abbrev_all(longname text) RETURNS TEXT
  DECLARE
   abbrev text;
  BEGIN
+  // make shure to call this before osml10n_street_abbrev_en
+  abbrev=osml10n_street_abbrev_fr(abbrev);
   abbrev=osml10n_street_abbrev_en(longname);
   abbrev=osml10n_street_abbrev_de(abbrev);
-  abbrev=osml10n_street_abbrev_fr(abbrev);
   abbrev=osml10n_street_abbrev_ru(abbrev);
   abbrev=osml10n_street_abbrev_uk(abbrev);
   return abbrev;
@@ -69,9 +70,10 @@ CREATE or REPLACE FUNCTION osml10n_street_abbrev_latin(longname text) RETURNS TE
  DECLARE
   abbrev text;
  BEGIN
+  // make shure to call this before osml10n_street_abbrev_en
+  abbrev=osml10n_street_abbrev_fr(abbrev);
   abbrev=osml10n_street_abbrev_en(longname);
   abbrev=osml10n_street_abbrev_de(abbrev);
-  abbrev=osml10n_street_abbrev_fr(abbrev);
   return abbrev;
  END;
 $$ LANGUAGE 'plpgsql' IMMUTABLE;
@@ -148,6 +150,9 @@ CREATE or REPLACE FUNCTION osml10n_street_abbrev_fr(longname text) RETURNS TEXT
  BEGIN
   abbrev=longname;
   abbrev=regexp_replace(abbrev,'^Avenue\M','Av.');
+  // this should fix the issue with invalid usage of english abbreviations in canada
+  abbrev=regexp_replace(abbrev,'^([0-9]+)e Avenue\M','\1e Av.');
+  abbrev=regexp_replace(abbrev,'^1ere Avenue\M','1ere Av.');
   abbrev=regexp_replace(abbrev,'^Boulevard\M','Bd');
   abbrev=regexp_replace(abbrev,'^Chemin\M','Ch.');
   abbrev=regexp_replace(abbrev,'^Esplanade\M','Espl.');
```

**Comment by chatelao** [comment]
Wie gesagt: Kommt - Aber ich schreib einen "one-off" für die Avenue's.

**Comment by chatelao** [comment]
Auswertung in Montreal, es gibt folgende Testfälle:

- 1er Avenue
- 1ere Avenue
- **1ère** Avenue
- **1re** Avenue

```
[out:csv (name; false)];
(
 way["highway"]["name"~"Avenue"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Comment by giggls** [comment]
Wie kürzt man den 1., 2., 3. generell auf französisch ab?

**Comment by chatelao** [comment]
https://francais.lingolia.com/fr/vocabulaire/nombres-date-et-heure/les-nombres-ordinaux - Besser könnte ich das wohl nicht beschreiben:
- Première = weiblich = 1re
- Premier = männlich = 1er

**Comment by chatelao** [comment]
In-Extremis könnte man gleich die Superscripte aus den Unicode Tabellen nehmen:

https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin_and_Greek_tables

1ʳᵉ Avenue / 2ᵉ Avenue etc. - Ob dies der Lesbarkeit dienlich wäre- wohl eher nicht. Und wahrscheinlich unterstützen nicht alle Fonts diese Zeichen.

**Comment by giggls** [comment]
Müsste das dann nicht 1re heißen, weil Avenue weiblich ist?

**Comment by giggls** [comment]
Da wir ohnehin nur Noto verwenden wäre das schnell überprüft.

**Comment by chatelao** [comment]
Passt doch. Vielleicht versuche ich für "en" den Lookback anzupassen, dass die Reihenfolge keine Rolle spielt. Aber da muss mir Google noch etwas helfen.

**Comment by giggls** [comment]
Eventuell mal visual-regexp anschaun, das verwende ich immer.

**Comment by chatelao** [comment]
Zur Ergänzung eine alternative Schreibweise mit Lookahead RegExp 🧙:

1. French: ```sql abbrev=regexp_replace(abbrev,'(?<=^|[0-9]re |[0-9]e )Avenue\M','Av.'); ```
2. English: ```sql abbrev=regexp_replace(abbrev,'(?<!^|[0-9]re |[0-9]e )Avenue\M','Ave.'); ```

**Comment by giggls** [comment]
Das erzeugt jedoch definitiv etwas anderes als mein Code.

Ich sehe gerade ich habe ein ^ zu viel, aber das stört anscheinend nicht.
So sollte das aussehen:
regexp_replace(abbrev,'^1[eè]?re Avenue\M','1re Av.');

Das erlaubt `1ere, 1ère und 1re`. Eventuell solle ich auch alle drei in einen Test stecken.

Wenn Du das was mein Code macht mit einem einzigen regexp_replace hinkriegst, dann mach mir einen pull request. In den Tests kannst Du ja sehen ob es klappt.

Es sollte aber halt schon das selbe tun wie mein Code.

Wenn ich Dein Regex richtig verstehe berücksichtigt er außerdem keine mehrstelligen Nummern.

22e Avenue oder so.

Was man IMO generell nicht machen sollte ist falsch gemapptes Zeug korrigieren, dass sollen die Mapper fixen, nicht die Nutzer der Daten.

**Comment by chatelao** [comment]
Kurze Erläuterung zum (vereinfachten) "positive lookbehind" ```(?<=^|1re |[0-9]e )Avenue\M```. Er prüft drei Fälle (Die Pipes "|" trennen die Fälle):

1. **^Avenue\M** - Der bisherige, allgemeine frz. Fall, am Anfang des Namens
1. **1re Avenue\M** - Die ersten Avenue(s) mit "re" (48x "1re Avenue" in Montréal")
1. **[0-9]e Avenue\M** - Alle anderen Avenues mit nummerischen+"e" Prefixes (95x "1e Avenue in Montréal")

Hier die verwendete Query: https://overpass-turbo.eu/s/O4f

Die beiden Fälle **1ère** und **1ere** hab ich nicht mit aufgenommen, weil sie in Montreal nur 1x resp. 2x vorkommen und in der allgemeinen Beschreibung der frz. Nummerierungen nicht erwähnt werden.

Fazit: Diese beiden Regeln sind in meinen lokalen Tests, ohne "1ere" und "1ère" erfolgreich:
- FR:
```sql
 abbrev=regexp_replace(abbrev,'(?<=^|1re |[0-9]e )Avenue\M','Av.');
```
- EN:
```sql
 abbrev=regexp_replace(abbrev,'(?<!^|1re |[0-9]e )Avenue\M','Ave.');
```

Englisch:
- src: https://github.com/chatelao/osm-abbrev/blob/master/plpgsql/street_abbrv.sql#L161
- tst: https://travis-ci.com/chatelao/osm-abbrev/builds/136365373#L1254 bis L1263

French:
- src: https://github.com/chatelao/osm-abbrev/blob/master/plpgsql/street_abbrv.sql#L255
- tst: https://travis-ci.com/chatelao/osm-abbrev/builds/136365373#L1200 bis 1207

=> Ich kann gerne einen spezifischen pull request erstellen und würde vorschlagen, dass wir "1ère" und "1ere" nicht berücksichtigen.

**Comment by giggls** [comment]
Ich finde mit 
```
[out:csv (name; false)];
(
 way["highway"]["name"~"^1[^0-9].* Avenue"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

folgendes in Montreal und Quebec:
```
1e Avenue
1re Avenue
1ère Avenue
1ere Avenue
```
Was davon jetzt falsch ist kann ich schlecht beurteilen. Ich würde falsche erfasste Namen eher unberücksichtigt lassen. Aber sind "1ère" und "1ere" wirklich falsch?

1e kommt mir auch eher falsch vor.

Sie deshalb weg zu lassen weil diese Art der Regular Expression das nicht kann oder (noch schlimmer) weil wir das nicht hinkriegen halte ich jedenfalls für keine gute Idee.

Was mir auch nicht gefällt ist dass dein Code 1re und 1e durchlässt. Da sollte ein einheitlicher Output rauskommen.

**Comment by chatelao** [comment]
1. Aufgrund des Mengengerüst würde mich wundern, wenn 1e als "falsch" beurteilt würde.
2. Die Idee mit dem Normalisieren tönt sympatisch.
3. Vorschlag:
  - 1e Avenue => 1re Ave.
  - 1re Avenue => 1re Ave.
  - 1[eè]re Avenue => 1re Ave.

Wäre das passend (Bei [èe]re bin ich schmerzlos)? Dann passe ich die Testfälle an und schreibe den Code um. Mir sind die RegExp sympatisch, weil der Code en/fr getrennt und in beliebieger Reihenfolge ausgeführt werden kann.

**Comment by giggls** [comment]
Ich denke das ist doch genau das was mein momentaner Code macht. Nur halt mit einer if Kaskade und nicht mit reinen regular expressions.

Das mit der beliebigen Reihenfolge erlaubt mein Code ja auch schon das mit der Änderung der Aufrufreihenfolge habe ich verworfen.

https://github.com/giggls/mapnik-german-l10n/compare/v2.5.7..master

**Comment by chatelao** [comment]
Noch eine Frage: Bis zu welcher PostGre Version zurück sollte der Code funktionieren?

PS: Wenn möglich, möchte langfristig alle "if/then/else" elimineren und nur eine Liste von Regeln führen. Aber muss nicht unbedingt sein.

**Comment by giggls** [comment]
Von mir aus, wenn Du die selbe Funktionalität rein mit Regular Expressions hinkriegst.
Momentan brauche ich wegen regexp_match mindestens PostgreSQL 10. Sollte ich im INSTALL.md mal anpassen.

**Comment by chatelao** [comment]
Im Debian Paket (https://github.com/giggls/mapnik-german-l10n/blob/master/debian/pgversions) wird v9.4+ erwähnt :-). Im control die v9.5 (https://github.com/giggls/mapnik-german-l10n/blob/master/debian/control).

Ich hätte fast angefangen, alles rückwärts zu portieren (geht ja irgendwie). Aber wenn das nicht nötig ist (kann ich nicht beurteilen), dann lassen wir das und schauen vorwärts nach 10/11.

**Comment by giggls** [comment]
9.4 is likely the version where I first started to develop this code. Fixed now.
