### ISSUE TITLE
Easy use in "CartoOSM" ?

### ISSUE THREAD

**Issue by chatelao** [giggls/mapnik-german-l10n#27]
Goal:
- Use https://github.com/gravitystorm/openstreetmap-carto
- Add the latin transliteration & abbreviation features

Question:
- Is there a simple, non-invasive way to do so?

Background:
- OSM-FR has an abbreviation hack
- OSM-CH has an abbreviation hack
- ....

It would be nice to have a simple, drop-in way to install it on a "OSMcarto" or derived map without a lot of changes to the map. Then it would be simple to promote the module and get more logic feeded in from the local communities and become the abbreviation reference source.

Any idea?

btw.:
Nominatin has an own logic (https://github.com/openstreetmap/Nominatim/blob/master/module/tokenstringreplacements.inc) too, but I will tackle this later :-)

The proposed documentation moved here, to be able to re-fork soon:
- https://github.com/chatelao/osm-documentation

**Comment by chatelao** [comment]
Maybe this view from maposmatic is close?

- https://github.com/chatelao/maposmatic-vagrant/blob/master/files/database/db_views/planet-osm-line.sql

**Comment by giggls** [comment]
Frankly, I do not understand your Problem.
Just use https://github.com/giggls/openstreetmap-carto-de/tree/upstream+l10n and you are done.
Using unchanged upstream Style is not possible because one has to express somewhere which Labels should be localized in which way.

**Comment by chatelao** [comment]
Thanks, I will have a look at it. Basically I'm searching a DB only solution to be used in any map - I'll keep you informed, this library is great to be used everywhere.
