### ISSUE TITLE
Add street abbreviations for norwegian (nb-NO)

### ISSUE THREAD

**Issue by atlefren** [giggls/mapnik-german-l10n#3]
Instead of messing up the code, I'll just provide the norwegian street type names and their abbreviations here

vei: v.
veg: v.
gate: gt.
alle: not sure
veite/veita: not sure
smug: not sure

Hope this is of any use, thanks for a great talk in Bonn!

**Comment by giggls** [comment]
Google does not seem to abbreviate them in Norway. Is it common to do so? It is very common in German and also seems to be in English. As Norwegian is a language using the Latin alphabet we will probably be better of to also not doing it. Looks like Norwegian names are short anyway :)

**Comment by atlefren** [comment]
True, they are not commonly abbreviated exept for exceptionally long names

**Comment by giggls** [comment]
OK, I will close this issue then.
