### ISSUE TITLE
Superscript code

### ISSUE THREAD

**Issue by chatelao** [giggls/mapnik-german-l10n#34]
This is some code to convert french and english cardinal numbers to superscripts. - If you like it and it looks better on the map, just pick the code you need. If you stay with the current way no problem at all.

English:
```sql
  abbrev=regexp_replace(abbrev,'1st\M','1ˢᵗ');
  abbrev=regexp_replace(abbrev,'2nd\M','2ⁿᵈ');
  abbrev=regexp_replace(abbrev,'3rd\M','3ʳᵈ');
```

French:
```
  abbrev=regexp_replace(abbrev,'^1re\M','1ʳᵉ');
  abbrev=regexp_replace(abbrev,'(?<=^[0-9]+)e\M','ᵉ');
```
More characters (if needed) here:
- https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin_and_Greek_tables

**Comment by giggls** [comment]
Looking at the actual map tiles I am afraid those will get mostly unreadable.
This said I might be able to render example tiles, but english Version seems to be  incomplete, right.

Untested:
```
abbrev=regexp_replace(abbrev,'([04-9])th\M','\1ᵗʰ');
```

**Comment by chatelao** [comment]
Thanks for Testing in tiles (my system is not yet render ready)
