### ISSUE TITLE
If there is no name:de use old_name:de

### ISSUE THREAD

**Issue by Spanholz** [giggls/mapnik-german-l10n#36]
Former german villages in Poland are often tagged with old_name:de=* instead of name:de=*. 

Is it possible/useful to add the old_name if there is no name:de-tag?

**Comment by giggls** [comment]
I think **not** doing this is exactly what should be done for political reasons especially in Poland.
You might also watch my talks linked in the [Wiki](https://github.com/giggls/mapnik-german-l10n/wiki) for further information about political issues of l10n.

**Comment by Spanholz** [comment]
I am completely aware of the political implications of adding the german village names. That's why I wrote "useful". It is probably more a problem of consistency in the tagging. Most villages are tagged with name:de=*, some with old_name:de=*. For most towns the german name is not the official name anymore but still they are tagged with it. 

I guess my questions is better suited for the polish community and how they want to handle the german name tags.

**Comment by giggls** [comment]
Excerpt from Slide 16 of my talk:

> Due to the lack of an alternative, we hope that mappers will only acquire names which are still used (or use old_name respectively)."

**Comment by dieterdreist** [comment]
Am Di., 10. Dez. 2019 um 15:18 Uhr schrieb Sven F. <notifications@github.com
>:

> For most towns the german name is not the official name anymore but still
> they are tagged with it.
>
>
most name:language tags are not "official names". The particular situation
in eastern Poland is that the names have been in use only for very few
years (during the war and German occupation), and Germans have generally
behaved so badly that it doesn't seem useful to refresh these memories.
Putting the war-names in OSM could also be seen as reactionary (depending
on the key you use). These are often not "old names", but ideological
artificial names that have been in use for not more than 5 years.

**Comment by giggls** [comment]
I close this issue now, as I will not use old_name:de for rendering.
