### ISSUE TITLE
tail +3

### ISSUE THREAD

**Issue by thomersch** [giggls/mapnik-german-l10n#37]
I am building the latest release [v2.5.8](https://github.com/giggls/mapnik-german-l10n/tree/v2.5.8) using `make deb` on Ubuntu 16.04.

This fails on the `osml10n--$(EXTVERSION_OLD)--$(EXTVERSION).sql: osml10n--$(EXTVERSION).sql` target, as the installed `tail` (GNU coreutils 8.25) doesn't have the `+3` option. Did you mean `tail -n +3`?

**Comment by giggls** [comment]
It is easier to port a shell than a shell script.
— Larry Wall 

I could have sworn this shortcut for `head -n +3` is way older that Ubuntu 16.04.

Obviously it is not. I will fix this in master.

**Comment by thomersch** [comment]
Awesome, thanks!

> [...] is way older that Ubuntu 16.04.

It's really weird indeed. Even my BSD tail from 2006 (!) knows it.
