### ISSUE TITLE
Error with missing column in views

### ISSUE THREAD

**Issue by Fauch922** [giggls/mapnik-german-l10n#57]
I have installed the plugin according to instructions. Everything seems to work okay, but from time to time, renderd produces the following error message:

RROR: failed to render TILE default 6 32-39 32-39
Nov 01 18:27:42 mapserverrenderd[59251]:    reason: Postgis Plugin: ERROR:  column "idxnl" does not exist
                                                   LINE 1: SELECT idxnl
                                                                  ^
                                                   QUERY:  SELECT idxnl
                                                   CONTEXT:  PL/pgSQL function osml10n_gen_combined_names(text,hstore,boolean,boolean,boolean,boolean) line 144 at assignment
                                                   PL/pgSQL function osml10n_get_names_from_tags(hstore,boolean,boolean,text,geometry) line 12 at RETURN
                                                   PL/pgSQL function osml10n_get_placename_from_tags(hstore,boolean,boolean,text,text,geometry,text) line 9 at assignment
                                                   in executeQuery Full sql was: 'SELECT ST_AsBinary("way") AS geom,"name","way_pixels" FROM (SELECT
                                                       ST_PointOnSurface(way) AS way,
                                                       way_area/NULLIF(POW(8.73566e+06*0.001*0.28,2),0) AS way_pixels,
                                                       localized_name_first as name,
                                                       ref
                                                     FROM planet_osm_polygon
                                                     WHERE way && ST_SetSRID('BOX3D(-313086.0678562499 -5322463.153556248,5322463.153556248 313086.0678562499)'::box3d, 3857)
                                                       AND boundary = 'administrative'
                                                       AND admin_level = '4'
                                                       AND name IS NOT NULL
                                                       AND way_area > 100*2445.98::real*2445.98::real
                                                       AND osm_id < 0
                                                     ORDER BY way_area DESC
                                                   ) AS state_names'

Some background info: I'm trying to use mapnik-german-I10n together with openstreetmap-carto-de. I have created the necessary views. I'm not exactly sure what's wrong - maybe the error is with my OSM import?
I could not find any reference to a column called idxnl save for in mapnik-german-I10n.

Best Regards

**Comment by giggls** [comment]
Apply the patch from pull request #56

**Comment by Fauch922** [comment]
Thank you for your reply and for your help.
I was simply unaware of the releases, so this is definitely on me.
