### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by stoecker** [giggls/mapnik-german-l10n#7]
Hi,

the default target variable is DESTDIR not TMPTARGET.

Can you please change this for easier RPM release.

**Comment by giggls** [comment]
Done. If you build a spec file please add an rpm target to the Makefile and do a pull request :)

**Comment by stoecker** [comment]
Here is the build stuff for the RPM. Don't know how or if it makes sense to integrate that into your repo.

https://build.opensuse.org/package/show/Application:Geo/osml10n

**Comment by giggls** [comment]
Does not if it is part of the distro anyway.
