### ISSUE TITLE
README.md: missing dep?

### ISSUE THREAD

**Issue by mmd-osm** [giggls/mapnik-german-l10n#8]
To fix errors during `make dep`, I had to to install the following package in addition what is listed in README.md on Ubuntu 16.04:

```
apt-get install postgresql-server-dev-all
```

Tested on https://github.com/giggls/mapnik-german-l10n/commit/f557ef17d93214b85a25ef83b9e42bb0d6508107

**Comment by giggls** [comment]
Hm it is never a good Idea to have stuff in more than one place. Thus I fixed INSTALL.md in dc6cb6eb0af2bd6d4a776bb9e3f4455da2ade640 to use mk-build-deps instead of manually calling apt-get install

**Comment by mmd-osm** [comment]
Basically ok for me. Unfortunately, `mk-build-deps` itself has some new dependencies...

```
apt install devscripts
```

Then I got the following message:

```
~/btrfs/mapnik-german-l10n$ sudo mk-build-deps -i debian/control
mk-build-deps: You must have equivs installed to use this program.
```

Let's install equivs then:

```
apt-get install equivs
```
